# -*- mode: ruby -*-
# vi: set ft=ruby :

#RCI, 2025 - Estudante: Jussana Paim

Vagrant.configure("2") do |config|
  # config.vm.box = "ktr/mininet"
  config.ssh.insert_key = false
  config.vbguest.auto_update = false

  # Bloco 1 - WebServer
  config.vm.define "webserver" do |web_config|
    web_config.vm.box = "ubuntu/trusty64"
    web_config.vm.hostname = "webserver"
    web_config.vm.network "private_network", ip: "192.168.56.21"
    #web_config.vm.network "forwarded_port", guest: 80, host: 8080
    web_config.vm.synced_folder "html", "/home/vagrant/html"

    # Configuração do VirtualBox para o webserver 
    web_config.vm.provider "virtualbox" do |vb|
      vb.name = "webserver"
      opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize opts
      vb.memory = "256"
    end #do vb

    #web_config.vm.provision "shell", path: "bootstrap_web.sh"
  end #do web_config

  # Bloco 2: client (IP 192.168.56.11)
  config.vm.define "client" do |client_config| 
    client_config.vm.box = "ubuntu/trusty64"
    client_config.vm.hostname = "client" 
    client_config.vm.network "private_network", ip: "192.168.56.11"
    client_config.vm.synced_folder "html", "/home/vagrant/html" # Sua única função é permitir que execute o script

    client_config.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      opts = ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize opts
      vb.memory = "256"
     end # of vb
     client_config.vm.provision "shell", path: "bootstrap-client.sh"
  end #do client
end #do config